// Generated by `prisma-composer deploy`/`prisma-composer destroy` — overwritten on every
// run; do not edit by hand. Runnable from "C:\\Users\\User\\Desktop\\Programmer\\Project\\TS_Money_Management_App\\server\\money_Management" WITH the env the
// CLI passes its child (the PRISMA_COMPOSER_CONTAINER_*/_PREFLIGHT_* vars —
// without them lower() refuses because no container is resolved):
//
//   alchemy deploy .prisma-composer/alchemy.run.ts
//
// bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
import { lower } from '@prisma/composer/deploy';
import { deploymentReport } from '@prisma/composer/report';
import config from "../prisma-composer.config.ts";
import app from "../module.ts";

export default lower(app, config, {
  name: "money_management",
  bundles: {
    "app": { dir: "C:\\Users\\User\\Desktop\\Programmer\\Project\\TS_Money_Management_App\\server\\money_Management\\.prisma-composer\\artifacts\\app", entry: "bundle/server.mjs" },
  },
  report: deploymentReport,
});
